version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "fix(deps)"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
  - package-ecosystem: "github-actions"
    directory: ".github"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "fix(deps)"